# comprehensive_test_config.yaml
# Configuration for LLM-ATC-HAL Comprehensive Hallucination Testing

# Model Configuration
models_to_test:
  - "llama3.1:8b"
  - "mistral:7b" 
  - "codellama:7b"

ensemble_weights:
  primary: 0.4
  validator: 0.3
  technical: 0.3

# Scenario Configuration  
num_scenarios: 2000  # Start with 2000, scale to 10,000+ for full thesis campaign
complexity_distribution:
  simple: 0.3
  moderate: 0.4
  complex: 0.2
  extreme: 0.1

# Testing Parameters
parallel_workers: 6  # Adjust based on system capabilities
timeout_per_test: 30.0

# Performance Thresholds (as specified in README with ICAO compliance)
target_accuracy: 0.85      # AUROC > 0.85 for hallucination detection
target_response_time: 2.0  # < 2s mean response time
target_safety_compliance: 0.95  # 95% ICAO compliance

# ICAO Standards Configuration (consistent across all modules)
icao_standards:
  horizontal_separation_nm: 5.0    # Both detection and ground truth
  vertical_separation_ft: 1000.0   # Both detection and ground truth  
  time_horizon_sec: 300.0          # Check conflicts within 300s
  conflict_detection_methods: ["SWARM", "STATEBASED", "ENHANCED"]
  cpa_analysis_enabled: true       # Include CPA in analysis and prompts

# Hardware Configuration
use_gpu_acceleration: true
batch_size: 32

# Output Configuration
output_directory: "output/comprehensive_testing"
generate_visualizations: true
detailed_logging: true

# Advanced Testing Options
edge_case_scenarios: true
monte_carlo_simulation: true
statistical_significance_testing: true
real_time_monitoring: true

# Research Data Collection
collect_research_data: true
export_dataset_format: "json"
include_session_logs: true
generate_thesis_metrics: true
