# Horizontal Conflict Resolution Environment Configuration
environment:
  name: "HorizontalCREnv-v0"
  action_space: 1  # heading changes only
  observation_space: 8  # 3 + 5*nac (assuming 1 aircraft)
  max_aircraft: 5
  scenario_types:
    - "head_on_conflict"
    - "crossing_conflict"
    - "overtaking_conflict"
    - "multi_aircraft_conflict"

# SAC Model Configuration
sac_model:
  model_path: "F:/LLM-ATC-HAL/BSKY_GYM_LLM/models_backup/horizontal_cr_sac"
  policy_type: "MlpPolicy"
  
# Data Generation
data_generation:
  num_episodes: 1000
  max_steps_per_episode: 200
  samples_per_environment: 10000
  expert_threshold: 0.8  # minimum performance to include sample
  
# LLM Fine-tuning Configuration
llm_training:
  base_model: "meta-llama/Llama-2-7b-hf"
  lora_config:
    r: 32
    lora_alpha: 64
    target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
    lora_dropout: 0.1
    bias: "none"
    task_type: "CAUSAL_LM"
  
  training_args:
    output_dir: "./models/horizontal_cr_llama"
    num_train_epochs: 3
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 4
    gradient_accumulation_steps: 8
    learning_rate: 2e-4
    warmup_steps: 100
    logging_steps: 10
    save_steps: 500
    eval_steps: 500
    evaluation_strategy: "steps"
    load_best_model_at_end: true
    metric_for_best_model: "eval_loss"
    greater_is_better: false
    fp16: true
    dataloader_num_workers: 4
    remove_unused_columns: false

# Prompting Templates
prompts:
  system_prompt: |
    You are an expert air traffic controller specializing in horizontal conflict resolution. 
    Your primary responsibility is to manage aircraft heading changes to avoid conflicts while 
    maintaining efficient flight paths to waypoints. Always prioritize safety while minimizing 
    flight time and fuel consumption.
    
    Key principles:
    - Maintain minimum 5 nautical mile horizontal separation
    - Minimize drift from optimal flight path
    - Consider relative speeds and closure rates
    - Make decisive, clear heading changes
    
    Response format: Provide heading change in degrees (positive for right turn, negative for left turn).
    
  user_prompt_template: |
    Situation: Aircraft at altitude {altitude}ft, current heading {heading}°, speed {speed}kts.
    Waypoint: Bearing {waypoint_bearing}° at {waypoint_distance}nm.
    Current drift from optimal path: {drift}°.
    
    Conflicting aircraft:
    {conflict_info}
    
    What heading change should be made? Consider:
    1. Maintaining separation from conflicts
    2. Minimizing drift to waypoint
    3. Efficient conflict resolution
    
    Provide your decision as a heading change in degrees.

# Safety and Performance Metrics
evaluation:
  safety_metrics:
    - "separation_violations"
    - "minimum_separation_distance"
    - "time_to_conflict"
  
  performance_metrics:
    - "waypoint_arrival_time"
    - "fuel_efficiency"
    - "drift_penalty"
    - "action_smoothness"
  
  success_criteria:
    min_separation: 5.0  # nautical miles
    max_drift: 30.0      # degrees
    completion_rate: 0.85 # fraction of successful scenarios
