# Sector Conflict Resolution Environment Configuration
environment:
  name: "SectorCREnv-v0"
  action_space: 2  # heading and speed changes
  observation_space: 10  # 3 + 7*nac (assuming 1 aircraft)
  max_aircraft: 8
  scenario_types:
    - "sector_exit"
    - "multi_conflict"
    - "high_density_traffic"
    - "crossing_sectors"

# SAC Model Configuration
sac_model:
  model_path: "data_generation/models_backup/SectorCREnv-v0/SectorCREnv-v0_SAC/model.zip"
  policy_type: "MlpPolicy"
  
# Data Generation
data_generation:
  num_episodes: 1500
  max_steps_per_episode: 400
  samples_per_environment: 15000
  expert_threshold: 0.75
  
# LLM Fine-tuning Configuration
llm_training:
  base_model: "meta-llama/Llama-2-7b-hf"
  ollama_model: "llama3.1:8b"  # Updated to use Llama 3.1 8B
  lora_config:
    r: 32
    lora_alpha: 64
    target_modules: ["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
    lora_dropout: 0.1
    bias: "none"
    task_type: "CAUSAL_LM"
  
  training_args:
    output_dir: "./models/sector_cr_llama"
    num_train_epochs: 4
    per_device_train_batch_size: 3
    per_device_eval_batch_size: 3
    gradient_accumulation_steps: 12
    learning_rate: 1.5e-4
    warmup_steps: 150
    logging_steps: 10
    save_steps: 500
    eval_steps: 500
    eval_strategy: "steps"
    load_best_model_at_end: true
    metric_for_best_model: "eval_loss"
    greater_is_better: false
    fp16: true
    dataloader_num_workers: 4
    remove_unused_columns: false

# Prompting Templates
prompts:
  system_prompt: |
    You are an expert air traffic controller managing a busy air traffic sector. 
    Your responsibility is to coordinate both heading and speed changes to ensure 
    safe and efficient traffic flow while aircraft exit the sector. You must handle 
    multiple conflicts simultaneously while maintaining optimal traffic throughput.
    
    Key principles:
    - Maintain minimum 5 nautical mile horizontal separation
    - Optimize sector exit efficiency
    - Coordinate multiple aircraft movements
    - Balance safety with traffic flow
    - Consider relative speeds and vectors
    
    Response format: Provide heading change in degrees and speed change in knots.
    
  user_prompt_template: |
    Situation: Aircraft in sector at position ({x_pos}, {y_pos}).
    Current heading: {heading}°, speed: {airspeed}kts.
    Drift from optimal sector exit path: {drift}°.
    Sector exit point: Bearing {exit_bearing}° at {exit_distance}nm.
    
    Traffic density: {traffic_count} aircraft in sector.
    
    Conflicting aircraft:
    {conflict_info}
    
    Nearby aircraft (non-conflicting):
    {traffic_info}
    
    What heading and speed changes should be made? Consider:
    1. Maintaining separation from all aircraft
    2. Efficient sector exit
    3. Overall traffic flow optimization
    4. Fuel efficiency
    
    Provide your decisions as:
    - Heading change: [X] degrees
    - Speed change: [Y] knots

# Safety and Performance Metrics
evaluation:
  safety_metrics:
    - "separation_violations"
    - "minimum_separation_distance"
    - "conflict_resolution_time"
    - "multi_conflict_handling"
  
  performance_metrics:
    - "sector_exit_time"
    - "fuel_efficiency"
    - "traffic_flow_efficiency"
    - "controller_workload"
  
  success_criteria:
    min_separation: 5.0      # nautical miles
    max_sector_time: 600     # seconds
    traffic_throughput: 0.90 # fraction of optimal
    completion_rate: 0.80
