# Enhanced Analysis Parameters for SCAT Dataset
# Phase 3: Comprehensive congestion analysis and ML hallucination research parameters

# 1. Control Center Workload Parameters (Swedish FIR specific)
control_center_workload:
  centers:
    esmm: # Stockholm ACC (Malmö)
      capacity_aircraft_per_hour: 180
      sectors: ["ESMM_N", "ESMM_S", "ESMM_E", "ESMM_W"]
      complexity_factors:
        domestic_traffic_weight: 0.6
        international_traffic_weight: 1.0
        military_coordination_weight: 1.3
        weather_coordination_weight: 1.2
      
    esos: # Stockholm ACC (Sundsvall)
      capacity_aircraft_per_hour: 120
      sectors: ["ESOS_N", "ESOS_S", "ESOS_C"]
      complexity_factors:
        domestic_traffic_weight: 0.5
        international_traffic_weight: 0.8
        arctic_operations_weight: 1.4
        winter_operations_weight: 1.5
  
  workload_calculation:
    base_time_per_aircraft_seconds: 45
    coordination_overhead_seconds: 15
    complexity_multipliers:
      simple_transit: 1.0
      level_change: 1.3
      route_deviation: 1.5
      emergency_handling: 2.5
      weather_coordination: 1.8

# 2. Operational Complexity Metrics
operational_complexity:
  holding_patterns:
    major_airports: ["ESSA", "ESGG", "ESMX", "ESMS"]
    holding_stack_levels: [7000, 8000, 9000, 10000, 11000]
    max_holding_time_minutes: 20
    complexity_weight: 1.5
  
  runway_operations:
    parallel_runway_complexity: 1.4
    crossing_runway_complexity: 1.8
    mixed_operations_complexity: 1.6
    weather_impact_multiplier: 1.3
  
  approach_procedures:
    ils_complexity: 1.0
    rnav_complexity: 1.2
    visual_complexity: 0.8
    circling_complexity: 2.0

# 3. Enhanced Temporal Granularity
temporal_analysis:
  micro_intervals:
    primary_minutes: 5
    secondary_minutes: 10
    tertiary_minutes: 15
  
  temporal_windows:
    burst_detection_minutes: 3
    congestion_assessment_minutes: 15
    trend_analysis_minutes: 60
  
  pattern_recognition:
    peak_duration_threshold_minutes: 30
    transition_period_minutes: 15
    baseline_stability_hours: 2

# 4. Separation and Safety Margins Analysis
safety_margins:
  minimum_separation:
    horizontal_nm: 5.0
    vertical_ft: 1000.0
    approach_horizontal_nm: 2.5
    approach_vertical_ft: 500.0
  
  safety_buffers:
    standard_buffer_factor: 1.2
    weather_buffer_factor: 1.5
    high_density_buffer_factor: 1.3
    emergency_buffer_factor: 2.0
  
  risk_assessment:
    conflict_prediction_horizon_minutes: 20
    separation_violation_threshold: 0.9
    near_miss_threshold_nm: 3.0
    safety_critical_threshold: 0.8

# 5. Communication and Coordination Complexity
communication_complexity:
  frequency_bands:
    primary_vhf: 118.0-137.0
    secondary_vhf: 121.5
    emergency_frequency: 121.5
    military_uhf: 225.0-400.0
  
  coordination_types:
    handoff_complexity: 1.0
    point_out_complexity: 0.7
    release_complexity: 0.8
    amendment_complexity: 1.3
    emergency_complexity: 2.5
  
  communication_workload:
    average_transmissions_per_flight: 8
    complex_clearance_factor: 1.5
    language_barrier_factor: 1.2
    emergency_communication_factor: 3.0

# 6. Meteorological Impact Parameters
meteorological_impact:
  weather_categories:
    clear: 
      visibility_km: ">10"
      wind_speed_kt: "<15"
      impact_factor: 1.0
    marginal:
      visibility_km: "5-10"
      wind_speed_kt: "15-25"
      impact_factor: 1.2
    adverse:
      visibility_km: "1-5"
      wind_speed_kt: "25-35"
      impact_factor: 1.5
    severe:
      visibility_km: "<1"
      wind_speed_kt: ">35"
      impact_factor: 2.0
  
  seasonal_factors:
    winter_operations: 1.4
    summer_storms: 1.3
    spring_variability: 1.2
    autumn_stability: 1.0
  
  specific_conditions:
    icing_conditions: 1.6
    turbulence_reports: 1.4
    low_visibility: 1.8
    crosswind_landings: 1.3

# 7. Aircraft Performance Characteristics  
aircraft_performance:
  wake_turbulence:
    heavy: # >136,000 kg
      separation_behind_nm: 6.0
      complexity_factor: 1.5
    medium: # 7,000-136,000 kg
      separation_behind_nm: 5.0
      complexity_factor: 1.0
    light: # <7,000 kg
      separation_behind_nm: 3.0
      complexity_factor: 0.8
  
  performance_categories:
    jet_transport:
      climb_rate_fpm: 2000
      cruise_speed_kt: 450
      complexity_factor: 1.0
    turboprop:
      climb_rate_fpm: 1200
      cruise_speed_kt: 250
      complexity_factor: 1.2
    general_aviation:
      climb_rate_fpm: 800
      cruise_speed_kt: 150
      complexity_factor: 1.5
  
  special_operations:
    military_aircraft: 1.8
    emergency_services: 2.0
    cargo_operations: 1.3
    training_flights: 1.4

# 8. Conflict Detection and Resolution Parameters
conflict_resolution:
  detection_parameters:
    time_horizon_minutes: [5, 10, 15, 20]
    conflict_probability_threshold: 0.7
    false_alarm_tolerance: 0.05
    missed_detection_tolerance: 0.01
  
  resolution_strategies:
    heading_change:
      min_degrees: 10
      max_degrees: 30
      complexity_factor: 1.0
    altitude_change:
      min_feet: 1000
      max_feet: 4000
      complexity_factor: 1.2
    speed_adjustment:
      min_percentage: 10
      max_percentage: 20
      complexity_factor: 0.8
    combined_maneuver:
      complexity_factor: 1.5
  
  resolution_effectiveness:
    success_rate_threshold: 0.95
    optimal_solution_preference: 0.8
    safety_margin_compliance: 0.99

# 9. Congestion Classification Parameters (4-Level System)
congestion_classification:
  levels:
    light:
      flights_per_hour: [0, 60]
      workload_factor: [0.2, 0.4]
      complexity_score: [0.0, 0.3]
      safety_margin: [0.8, 1.0]
      color_code: "green"
    
    normal: 
      flights_per_hour: [60, 120]
      workload_factor: [0.4, 0.7]
      complexity_score: [0.3, 0.6]
      safety_margin: [0.6, 0.8]
      color_code: "yellow"
    
    congested:
      flights_per_hour: [120, 180]
      workload_factor: [0.7, 0.9]
      complexity_score: [0.6, 0.8]
      safety_margin: [0.4, 0.6]
      color_code: "orange"
    
    extreme:
      flights_per_hour: [180, 250]
      workload_factor: [0.9, 1.0]
      complexity_score: [0.8, 1.0]
      safety_margin: [0.2, 0.4]
      color_code: "red"
  
  transition_thresholds:
    hysteresis_factor: 0.1
    minimum_duration_minutes: 10
    classification_confidence: 0.85

# 10. Monte Carlo Simulation Parameters
monte_carlo_simulation:
  iterations:
    quick_analysis: 1000
    standard_analysis: 5000
    comprehensive_analysis: 10000
  
  uncertainty_modeling:
    position_uncertainty_m: 50
    altitude_uncertainty_ft: 100
    time_uncertainty_s: 5
    speed_uncertainty_kt: 10
  
  scenario_generation:
    traffic_density_variations: [-0.2, -0.1, 0.0, 0.1, 0.2]
    weather_impact_variations: [1.0, 1.2, 1.5, 1.8, 2.0]
    equipment_failure_probability: 0.001
    emergency_scenario_probability: 0.005
  
  statistical_analysis:
    confidence_levels: [0.90, 0.95, 0.99]
    bootstrap_samples: 1000
    convergence_criteria: 0.01

# 11. Swedish FIR Specific Parameters
swedish_fir_parameters:
  geographic_sectors:
    stockholm_tma:
      center: [59.6517, 17.9186]
      radius_nm: 50
      complexity_factor: 1.5
    gothenburg_tma:
      center: [57.6628, 12.2944]
      radius_nm: 40
      complexity_factor: 1.3
    malmo_tma:
      center: [55.5364, 13.3703]
      radius_nm: 30
      complexity_factor: 1.2
  
  cross_border_coordination:
    denmark_coordination: 1.2
    norway_coordination: 1.1
    finland_coordination: 1.3
    estonia_coordination: 1.4
    
  seasonal_operational_factors:
    midnight_sun_period: # May-July
      controller_fatigue_factor: 1.2
      wildlife_interference: 1.1
    polar_night_period: # November-January  
      weather_complexity: 1.4
      equipment_reliability: 0.95
    
  special_airspace:
    military_restricted_areas: 1.8
    nature_reserves: 1.2
    noise_abatement_procedures: 1.3

# Enhanced Analytics and ML Parameters
enhanced_analytics:
  hallucination_detection:
    consistency_threshold: 0.85
    temporal_coherence_window: 300  # seconds
    spatial_coherence_radius: 5     # nautical miles
    confidence_degradation_rate: 0.1
  
  pattern_recognition:
    anomaly_detection_sensitivity: 0.95
    clustering_algorithms: ["dbscan", "kmeans", "hierarchical"]
    time_series_decomposition: true
    seasonal_trend_analysis: true
  
  predictive_modeling:
    forecast_horizon_minutes: [15, 30, 60, 120]
    model_validation_split: 0.2
    ensemble_methods: true
    feature_importance_threshold: 0.1

# Baseline Computation Enhanced Parameters  
baseline_computation:
  temporal_granularity:
    micro_intervals: [5, 10, 15]  # minutes
    standard_intervals: [30, 60]  # minutes
    macro_intervals: [120, 240]   # minutes
  
  seasonal_analysis:
    seasons: [spring, summer, autumn, winter]
    month_mapping:
      spring: [3, 4, 5]
      summer: [6, 7, 8] 
      autumn: [9, 10, 11]
      winter: [12, 1, 2]
  
  weekly_patterns:
    weekday_categories: [weekday, weekend]
    time_periods: [night, morning, afternoon, evening]
    hour_mapping:
      night: [0, 1, 2, 3, 4, 5]
      morning: [6, 7, 8, 9, 10, 11]
      afternoon: [12, 13, 14, 15, 16, 17]
      evening: [18, 19, 20, 21, 22, 23]
  
  congestion_metrics:
    workload_calculation_method: "time_based"
    safety_margin_calculation: "dynamic"
    complexity_aggregation: "weighted_sum"

# Advanced Visualization Parameters
visualization:
  congestion_heatmaps:
    resolution_degrees: 0.1
    time_resolution_minutes: 15
    interpolation_method: "bilinear"
  
  temporal_analysis:
    smoothing_window: 5
    trend_line_confidence: 0.95
    change_point_detection: true
  
  interactive_features:
    zoom_capability: true
    time_slider: true
    layer_control: true
    export_formats: [png, svg, html, pdf]

# Quality Assurance Parameters
quality_assurance:
  data_validation:
    completeness_threshold: 0.95
    accuracy_threshold: 0.98
    consistency_checks: true
  
  baseline_validation:
    statistical_significance: 0.05
    cross_validation_folds: 5
    bootstrap_confidence: 0.95
  
  output_verification:
    sanity_check_ranges: true
    comparative_analysis: true
    expert_review_threshold: 0.1
